/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommentStyle: typeof import('./../src/components/CommentStyle.vue')['default']
    DanPlayer: typeof import('@wiidede/dan-player')['DanPlayer']
    Scrubber: typeof import('./../src/components/Scrubber.vue')['default']
  }
}
