/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommentStyle: typeof import('./../src/components/CommentStyle.vue')['default']
    DanPlayer: typeof import('@wiidede/dan-player')['DanPlayer']
    Scrubber: typeof import('./../src/components/Scrubber.vue')['default']
    SubtitleStyle: typeof import('./../src/components/SubtitleStyle.vue')['default']
  }
}
