/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Comp: typeof import('dan-player')['DanPlayer']
    DanPlayer: typeof import('dan-player')['DanPlayer']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    HoverCard: typeof import('./../src/components/ui/hover-card/HoverCard.vue')['default']
    HoverCardContent: typeof import('./../src/components/ui/hover-card/HoverCardContent.vue')['default']
    HoverCardTrigger: typeof import('./../src/components/ui/hover-card/HoverCardTrigger.vue')['default']
    Label: typeof import('./../src/components/ui/label/Label.vue')['default']
    NumberField: typeof import('./../src/components/ui/number-field/NumberField.vue')['default']
    NumberFieldContent: typeof import('./../src/components/ui/number-field/NumberFieldContent.vue')['default']
    NumberFieldDecrement: typeof import('./../src/components/ui/number-field/NumberFieldDecrement.vue')['default']
    NumberFieldIncrement: typeof import('./../src/components/ui/number-field/NumberFieldIncrement.vue')['default']
    NumberFieldInput: typeof import('./../src/components/ui/number-field/NumberFieldInput.vue')['default']
    Slider: typeof import('./../src/components/ui/slider/Slider.vue')['default']
  }
}
