/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HoverCard: typeof import('./components/ui/hover-card/HoverCard.vue')['default']
    HoverCardContent: typeof import('./components/ui/hover-card/HoverCardContent.vue')['default']
    HoverCardTrigger: typeof import('./components/ui/hover-card/HoverCardTrigger.vue')['default']
  }
}
