/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommentStyle: typeof import('./components/CommentStyle.vue')['default']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Scrubber: typeof import('./components/Scrubber.vue')['default']
  }
}
